language: php

php:
  - 8.0

arch:
  - amd64
  - arm64

services:
  - docker

notifications:
  email:
    - team@appwrite.io

before_script: 
  - >
    if [ ! -z "${DOCKERHUB_PULL_USERNAME:-}" ]; then
      echo "${DOCKERHUB_PULL_PASSWORD}" | docker login --username "${DOCKERHUB_PULL_USERNAME}" --password-stdin
    fi
  - docker --version
  # Install latest Compose
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/1.29.2/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - composer install --ignore-platform-reqs
  - runtimes/buildLocalOnly.sh

script:
  - docker-compose up -d
  - docker-compose exec tests vendor/bin/phpunit --debug
  - docker-compose exec tests vendor/bin/psalm --show-info=true
